[workspace]
members = [
  "advance-runner",
  "contracts",
  "data",
  "dispatcher",
  "graphql-server",
  "grpc-interfaces",
  "http-health-check",
  "indexer",
  "inspect-server",
  "redacted",
  "rollups-events",
  "state-server",
  "test-fixtures",
  "types",
]
