[package]
name = "state-server"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"
authors = [
  "Gabriel Coutinho <gabriel.coutinho@cartesi.io>",
  "Roman HodulÃ¡k <roman.hodulak@cartesi.io>",
]


[[bin]]
name = "rollups_state_server"
path = "src/rollups_state_server.rs"

[[bin]]
name = "input_state_server"
path = "src/input_state_server.rs"

[[bin]]
name = "output_state_server"
path = "src/output_state_server.rs"

[[bin]]
name = "fee_manager_state_server"
path = "src/fee_manager_state_server.rs"

[[bin]]
name = "validator_manager_state_server"
path = "src/validator_manager_state_server.rs"



[dependencies]
block-history = { version = "0.3", registry = "cartesi" }
state-fold = { version = "0.3", registry = "cartesi" }
state-fold-types = { version = "0.3", registry = "cartesi" }
state-server-lib = { version = "0.3", registry = "cartesi" }

types = { path = "../types" }

anyhow = "1"
serde = "1"
snafu = "0.7"
structopt = "0.3"

tokio = { version = "1", features = ["macros", "sync", "rt-multi-thread"] }
tracing = "0.1"
