[package]
name = "inspect-server"
license = "Apache-2.0"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "inspect-server"
path = "src/main.rs"

[dependencies]
actix-web = "4.1"
actix-cors = "0.6"
anyhow = "1"
env_logger = "0.9"
hex = "0.4"
log = "0.4"
prost = "0.10"
regex = "1"
serde = { version = "1.0", features = ["rc", "derive"] }
snafu = "0.6"
structopt = "0.3"
tokio = { version = "1.19", features = ["macros", "time", "rt-multi-thread"] }
toml = "0.5"
tonic = "0.7"
uuid = { version = "1.2", features = ["v4"] }

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3"
serial_test = "0.7"

[build-dependencies]
tonic-build = "0.7"
