[package]
name = "http-health-check"
license = "Apache-2.0"
version = "0.9.0"
edition = "2021"

[dependencies]
axum = "0.6"
hyper = "0.14"
clap = { version = "4.0", features = ["derive", "env"] }
snafu = "0.7"
tracing = "0.1"
