[package]
name = "contracts"
license = "Apache-2.0"
version = "0.7.0"
edition = "2021"
authors = [
  "Gabriel Coutinho <gabriel.coutinho@cartesi.io>",
  "Roman HodulÃ¡k <roman.hodulak@cartesi.io>",
]

[dependencies]
state-fold-types = { features = ["ethers"], version = "0.5", registry = "cartesi" }
serde_json = "1"

[build-dependencies]
state-fold-types = { features = ["ethers"], version = "0.5", registry = "cartesi" }
serde_json = "1"
