[package]
name = "contracts"
license = "Apache-2.0"
version = "0.9.0"
edition = "2021"
authors = [
  "Felipe Argento <felipe@cartesi.io>",
  "Gabriel Coutinho <gabriel.coutinho@cartesi.io>",
  "Roman HodulÃ¡k <roman.hodulak@cartesi.io>",
]

[dependencies]
state-fold-types = { version = "0.6", registry = "cartesi", features = ["ethers"] }

[build-dependencies]
state-fold-types = { version = "0.6", registry = "cartesi", features = ["ethers"] }

[package.metadata.cargo-machete]
ignored = ["state-fold-types"]
