[package]
name = "types"
version = "0.8.0"
edition = "2021"
authors = [
  "Felipe Argento <felipe.argento@cartesi.io>",
  "Gabriel Coutinho <gabriel.coutinho@cartesi.io>",
  "Roman HodulÃ¡k <roman.hodulak@cartesi.io>",
]

[dependencies]
state-fold = { version = "0.6", registry = "cartesi" }
state-fold-types = { version = "0.6", registry = "cartesi", features = ["ethers"] }

anyhow = "1"
async-trait = "0.1"
contracts = { path = "../contracts" }
im = { version = "15", features = ["serde"] }
serde = { version = "1", features = ["rc"] }
